= Thymeleaf / Reactive Demo

This project is a baseline to play around with some reactive features of the upcoming Spring and Thymeleaf releases.

Nothing fancy here except the use of:

. WebClient from spring-webflux
. Flux / Mono from projectreator
. The latest Thymeleaf Milestone release to enable the reactive parts (Server-Side Events)

== About
The application retrieves data from the https://swapi.co/api[StarWars API] and renders it in a table declared in a Thymeleaf template.

== Playing around
You can use a switch in the `application.properties` to customize the behaviour of the application:

    swapp.reactive=false/true # if false: experience the old-fashioned sync behaviour

=== Running the app
The app has no custom port configured and will run on _http://localhost:8080_.
To start the app just type `./mvnw spring-boot:run` in the commandline.

== Info
This project uses the https://github.com/thymeleaf/thymeleafsandbox-sse-webflux/blob/6f51fbae29c30d273a1683a46ffead26ae942738/src/main/java/thymeleafsandbox/sseflux/SSEFluxWebConfig.java[WebConfig] from the Thymeleaf sample project to get started.
If there will be a _thymeleaf-spring5_ spring-boot-starter this config class gets obsolete.